services:
  postgres:
    image: postgres:16
    container_name: test_postgre
    restart: always
    environment:
      POSTGRES_USER: test_postgre
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
